JhumanJ/OpnForm

- app/Http/Controllers/Auth/UserController.php
- app/Http/Controllers/Forms/FormController.php
- app/Http/Resources/FormResource.php
- app/Http/Resources/UserResource.php
- app/Models/Forms/Form.php
- app/Models/User.php
When there was more forms, was took more time
So Improved DB performance & loading times
> Improved DB performance & loading times

- app/Http/Controllers/SitemapController.php
- app/Http/Controllers/TemplateController.php
- app/Http/Requests/Templates/CreateTemplateRequest.php
- app/Models/Template.php
- app/Models/User.php
- config/services.php
- database/migrations/2022_09_22_092205_create_templates_table.php
- database/migrations/2022_09_26_084721_add_questions_to_templates.php
- resources/js/components/open/forms/components/FormFieldsEditor.vue
- resources/js/components/open/forms/components/FormSubmissions.vue
- resources/js/components/pages/OpenFormFooter.vue
- resources/js/components/pages/forms/CreateTemplateModal.vue
- resources/js/components/templates/QuestionsEditor.vue
- resources/js/pages/forms/create.vue
- resources/js/pages/forms/show.vue
- resources/js/pages/templates/show.vue
- resources/js/pages/templates/templates.vue
- resources/js/router/routes.js
- resources/js/store/modules/open/templates.js
- routes/api.php
- tests/Feature/TemplateTest.php
SEO improvements for templates
and support for FAQ
> B8f7a improve templates pages for seo

- tailwind.config.js
Fix logic button class issue with Tailwind
> fix button UI issue

- app/Rules/FormPropertyLogicRule.php
- app/Service/Forms/FormLogicConditionChecker.php
- resources/js/components/open/forms/components/form-logic-components/ColumnCondition.vue
- resources/js/components/open/forms/components/form-logic-components/GroupControlSlot.vue
- resources/js/forms/FormLogicConditionChecker.js
- tests/Feature/Forms/FormLogicTest.php
Fix logic condition for multi select field
> Fix logic for multi select

- resources/js/components/open/forms/components/FormFieldsEditor.vue
- resources/js/components/open/forms/fields/FormBlockOptionsModal.vue
- resources/js/components/open/forms/fields/FormFieldOptionsModal.vue
Allow user to create duplicate block from existing block
> New Feature: Duplicate block

- app/Http/Controllers/Forms/PublicFormController.php
- app/Http/Requests/AnswerFormRequest.php
- app/Http/Requests/UserFormRequest.php
- app/Http/Resources/FormResource.php
- app/Models/Forms/Form.php
- database/factories/FormFactory.php
- database/migrations/2022_10_07_122038_add_visibility_to_forms.php
- resources/js/components/open/forms/components/form-components/FormInformation.vue
- resources/js/pages/forms/create.vue
- resources/js/pages/forms/show.vue
- resources/js/pages/home.vue
- tests/Feature/Forms/AnswerFormTest.php
Draft form won't be accessible
> New feature visibility - public/draft

- app/Http/Controllers/Forms/FormSubmissionController.php
- app/Http/Resources/FormResource.php
- app/Service/Forms/FormSubmissionFormatter.php
- resources/js/components/forms/components/VSwitch.vue
- resources/js/components/open/forms/components/FormSubmissions.vue
- tailwind.config.js
- Form Submissions table user can change display columns/fields
- in CSV export with removed fields
> Choose Visible columns & in csv with removed field

- app/Http/Controllers/Forms/FormController.php
- resources/js/pages/forms/show.vue
- resources/js/pages/home.vue
- resources/js/store/modules/open/forms.js
- tests/Feature/Forms/FormTest.php
When have more forms look some time to load 
so apply pagination
> Pagination for forms on main page

- app/Http/Requests/UserFormRequest.php
- resources/js/components/forms/CheckboxInput.vue
- resources/js/components/forms/FlatSelectInput.vue
- resources/js/components/forms/ToggleSwitchInput.vue
- resources/js/components/forms/index.js
- resources/js/components/open/forms/OpenForm.vue
- resources/js/components/open/forms/fields/FormFieldOptionsModal.vue
For change UI of checkbox to toggle switch
> Allow use of toggle switches for checkboxes

- app/Http/Controllers/Auth/RegisterController.php
- resources/js/components/forms/CheckboxInput.vue
- resources/js/pages/auth/login.vue
- resources/js/pages/auth/register.vue
- tests/Feature/RegisterTest.php
New UI for login & register page
> D7783 login & register page opnform

- resources/js/components/pages/OpenFormFooter.vue
- resources/js/pages/auth/ForgotPasswordModal.vue
- resources/js/pages/auth/login.vue
> C8292 reset password modal component + check reset screen

- resources/js/components/common/Button.vue
- resources/js/pages/settings/account.vue
- resources/js/pages/settings/admin.vue
- resources/js/pages/settings/billing.vue
- resources/js/pages/settings/index.vue
- resources/js/pages/settings/password.vue
- resources/js/pages/settings/profile.vue
- resources/js/pages/settings/workspace.vue
Can you please check workspace settings for polish UI
> New UI For Settings Page

- README.md
- database/migrations/2021_10_13_142022_create_users_workspaces_table.php
- storage/clockwork/.gitignore
Hi guys! I was here to write some doc wheb I have issues trying to install OpnForm locally.
So, you'll find:
- Documentation for the installation
- Some fixes in a migration: useless DB Transaction (not so useless after reading the process, but don't work with MariaDB here), and fixes malformed foreign keys constraints
- .gitignore for the `storage/clockwork` folder
> Some fixes and installation documentation

- app/Service/Forms/FormLogicConditionChecker.php
- Fix a logic check bug if value not in form param
- Fix isEmpty condition checker
> Fix a logic check bug if value not in form param

- resources/js/components/open/forms/fields/FormFieldOptionsModal.vue
> fix change field type issue for select field

- config/links.php
- package-lock.json
- resources/js/components/Navbar.vue
- resources/js/components/open/forms/fields/FormFieldOptionsModal.vue
> fix: navbar help link

- .env.docker
- .gitignore
- Makefile
- README.md
- docker-compose.yml
- php-cli.Dockerfile
Hi there 👋
I wanted to give this project a try and have gone ahead and added a simple docker-compose setup.
`make up` executes all necessary setup tasks as described in the `README.md` and runs the application on `localhost:4000`. The only requirements to use this are `make`, `docker` and `docker compose`.
This might be a solution to #50 . I'm open for suggestions and changes 😊
> Add docker compose setup

- resources/js/components/common/Notifications.vue
- resources/js/components/open/forms/components/FormEditor.vue
- resources/js/pages/forms/create.vue
- resources/js/pages/forms/edit.vue
@JhumanJ  Please test on your local before merge this
> Update dirty forms editor

- docker/php-fpm-wrapper.sh
- docker/redis-wrapper.sh
This should fix the redis persistence issue #331
> Issue 331 - Fix failing redis persistence

- api/app/Models/Workspace.php
- client/components/global/PoweredBy.vue
- client/components/open/forms/OpenCompleteForm.vue
- client/components/open/forms/components/form-components/FormEditorPreview.vue
- client/lib/forms/FormModeStrategy.js
@JhumanJ Can you please change logo here
> Better powered by button
